name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: fazenda451
          BRANCH_NAME: output
          THEME: tokyonight
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}